### ISSUE TITLE
docker-compose에서 관리하는 MySQL 컨테이너를 클라우드 서버로 마이그레이션 한다.

### ISSUE THREAD

**Issue by zeze1004** [zeze1004/wedding-jira-backend#104]
## 🖊️ *Description*
mysql 컨테이너 운영 비용이 더 크다고 판단해 클라우드 DB를 사용하기로 함

## ✅ *Todo*
- [x] naver cloud MySql DB 구매
- [x] docker-compose 스크립트 수정
- [x] 애플리케이션이 클라우드 DB 바라보게 엔드포인트 수정
