### ISSUE TITLE
JMeter를 사용해 Email 인증 임시 코드 DB와 로컬캐시간 성능 분석

### ISSUE THREAD

**Issue by zeze1004** [zeze1004/wedding-jira-backend#109]
## 🖊️ *Description*
Email 인증 코드 저장 시 로컬캐시와 DB 중 어느게 성능이 더 좋은지 비교하기

## ✅ *Todo*
- [ ] DB애 Email 인증 관련 쿼리 보내기
- [ ] JMeter 스크립트 짜기
- [ ] DB와 로컬캐시 사용 로직에 대해 각각 `/sendEmailVerificationCode` 쿼리 보내서 성능 비교하기

**Comment by zeze1004** [comment]
로컬에서 Jmeter 테스트 결과

## 이메일 인증 시 로컬 캐시를 활용한 회원가입 로직 구현
### 주요 내용
회원가입 시 유저의 이메일로 전송된 인증 코드를 로컬 캐시에 저장하여, 인증코드 검증 시 추가 I/O 시간을 절약하고 빠르게 처리하도록 구현
로컬 캐시에 인증 코드와 이메일 정보를 저장함으로써 인증 시간(캐시 TTL) 내에 입력한 사용자만 회원가입이 가능하도록 설계

### 기여한 점
JMeter를 활용한 성능 비교 테스트를 통해 데이터베이스 사용 대비 로컬 캐시 사용 시 인증 코드 조회 속도가 약 2배 빠르다는 것을 검증
캐시 TTL을 적용해 서버 부하를 줄이고, 인증 시간이 지난 경우의 예외 처리 로직을 구현하여 서비스 사용성 향상

- 사용스킬: Java, Spring, MySQL, Ehcache, JMeter

### 성과
데이터베이스에서 인증코드를 가져오는 것보다 로컬 캐시를 이용해 인증 처리 속도를 약 2배 향상
