### ISSUE TITLE
ApiResponse 리팩토링

### ISSUE THREAD

**Issue by zeze1004** [zeze1004/wedding-jira-backend#17]
## 🖊️ *Description*
ApiResponse 코드를 이해하기 쉽게 수정하다.

## ✅ *Todo*
- [x]  성공응답 메소드 수정
- [x] 예외응답 메소드 명 수정
- [ ] 성공응답과 에러응답 분리

**Comment by zeze1004** [comment]
응답 로직 개선은 우선순위가 낮아 이슈 closed하고 필요시 재 open
