### ISSUE TITLE
[Todo] Controller 통합테스트 실행

### ISSUE THREAD

**Issue by zeze1004** [zeze1004/wedding-jira-backend#47]
## 🖊️ *Description*
Todo API에 대한 통합테스트를 실시한다.
## ✅ *Todo*
- [ ] Todo 생성 테스트 통과
- [ ] Todo 수정 테스트 통과
- [ ] Todo 조회 테스트 통과
- [ ] Todo 삭제 테스트 통과

## 📗 *Etc*
- 테스트 커버리지 80% 이상

**Comment by zeze1004** [comment]
통합테스트는 우선순위가 낮아 이슈 closed하고 필요시 재 open
