### ISSUE TITLE
[Infra] 배포 이슈 수정

### ISSUE THREAD

**Issue by zeze1004** [zeze1004/wedding-jira-backend#91]
## 🖊️ *Description*
더 이상 세션을 사용하지 않으므로 Redis 설정을 제거한다.
dev 환경 로그를 수정한다.
## ✅ *Todo*
- [x] Spring-Redis 설정 제거
- [x] error 로그 터미널에 출력하도록 수정
- [x] 배포 스크립트 수정
