### ISSUE TITLE
Github Actions와 Docker-compose 환경변수 설정

### ISSUE THREAD

**Issue by zeze1004** [zeze1004/wedding-jira-backend#99]
## 🖊️ *Description*
Github Actions의 secret을 사용해 DB 환경변수 추가한다.

## ✅ *Todo*
- [x] Github Actions 스크립트 수정
- [x] Docker-compose-dev 환경변수 수정
- [x] 개발 이미지 배포
